services:
  account-service:
    image: ${REGISTRY}/account-service:latest
    build:
      context: services/account
      dockerfile: Dockerfile

  general-service:
    image: ${REGISTRY}/general-service:latest
    build:
      context: services/general
      dockerfile: cmd/server/Dockerfile
