// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: history.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createHistory = `-- name: CreateHistory :exec
INSERT INTO payment.histories(wallet_id, amount, description)
VALUES($1, $2, $3)
`

type CreateHistoryParams struct {
	WalletID    uuid.UUID
	Amount      int64
	Description string
}

func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) error {
	_, err := q.db.Exec(ctx, createHistory, arg.WalletID, arg.Amount, arg.Description)
	return err
}

const getHistoriesByWallet = `-- name: GetHistoriesByWallet :many
SELECT id, wallet_id, amount, description, created_at FROM payment.histories WHERE wallet_id = $1
`

func (q *Queries) GetHistoriesByWallet(ctx context.Context, walletID uuid.UUID) ([]PaymentHistory, error) {
	rows, err := q.db.Query(ctx, getHistoriesByWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentHistory
	for rows.Next() {
		var i PaymentHistory
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Amount,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
