// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
)

type PaymentHistory struct {
	ID       uuid.UUID
	WalletID uuid.UUID
	Amount   int64
	Detail   string
}

type PaymentWallet struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Amount int64
}
