// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentHistory struct {
	ID          uuid.UUID
	WalletID    uuid.UUID
	Amount      int64
	Description string
	CreatedAt   pgtype.Timestamptz
}

type PaymentWallet struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Balance int64
}
