// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wallet.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :exec
INSERT INTO payment.wallets(user_id)
VALUES($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) CreateWallet(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createWallet, userID)
	return err
}

const getWallet = `-- name: GetWallet :one
SELECT id, user_id, balance FROM payment.wallets WHERE user_id = $1
`

func (q *Queries) GetWallet(ctx context.Context, userID uuid.UUID) (PaymentWallet, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var i PaymentWallet
	err := row.Scan(&i.ID, &i.UserID, &i.Balance)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE payment.wallets
SET balance = balance + $1
WHERE id = $2
`

type UpdateWalletBalanceParams struct {
	Amount int64
	ID     uuid.UUID
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.Amount, arg.ID)
	return err
}
