// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wallet.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :exec
INSERT INTO payment.wallets(user_id)
VALUES($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) CreateWallet(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createWallet, userID)
	return err
}

const depositWallet = `-- name: DepositWallet :exec
UPDATE payment.wallets
SET amount = amount + $1
WHERE user_id = $2
`

type DepositWalletParams struct {
	DepositAmount int64
	UserID        uuid.UUID
}

func (q *Queries) DepositWallet(ctx context.Context, arg DepositWalletParams) error {
	_, err := q.db.Exec(ctx, depositWallet, arg.DepositAmount, arg.UserID)
	return err
}

const getWallet = `-- name: GetWallet :one
SELECT amount FROM payment.wallets WHERE user_id = $1
`

func (q *Queries) GetWallet(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var amount int64
	err := row.Scan(&amount)
	return amount, err
}

const withdrawWallet = `-- name: WithdrawWallet :exec
UPDATE payment.wallets
SET amount = amount - $1
WHERE user_id = $2
`

type WithdrawWalletParams struct {
	WithdrawAmount int64
	UserID         uuid.UUID
}

func (q *Queries) WithdrawWallet(ctx context.Context, arg WithdrawWalletParams) error {
	_, err := q.db.Exec(ctx, withdrawWallet, arg.WithdrawAmount, arg.UserID)
	return err
}
