// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attempt.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO general.material_attempts(material_id, student_id, score)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateAttemptParams struct {
	MaterialID uuid.UUID
	StudentID  uuid.UUID
	Score      *int32
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAttempt, arg.MaterialID, arg.StudentID, arg.Score)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAttemptsByMaterial = `-- name: GetAttemptsByMaterial :many
SELECT id, material_id, student_id, score, created_at
FROM general.material_attempts
WHERE material_id = $1 AND student_id = $2
`

type GetAttemptsByMaterialParams struct {
	MaterialID uuid.UUID
	StudentID  uuid.UUID
}

func (q *Queries) GetAttemptsByMaterial(ctx context.Context, arg GetAttemptsByMaterialParams) ([]GeneralMaterialAttempt, error) {
	rows, err := q.db.Query(ctx, getAttemptsByMaterial, arg.MaterialID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneralMaterialAttempt
	for rows.Next() {
		var i GeneralMaterialAttempt
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.StudentID,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
