// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package database

import (
	"context"
)

const createCategory = `-- name: CreateCategory :exec
INSERT INTO general.categories(name) VALUES($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) CreateCategory(ctx context.Context, category string) error {
	_, err := q.db.Exec(ctx, createCategory, category)
	return err
}
