// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: course.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addCourseCategory = `-- name: AddCourseCategory :exec
INSERT INTO course.course_categories(course_id, category_id) VALUES (
    $1,
    (SELECT id FROM course.categories WHERE name = $2)
)
`

type AddCourseCategoryParams struct {
	ID       uuid.UUID
	Category string
}

func (q *Queries) AddCourseCategory(ctx context.Context, arg AddCourseCategoryParams) error {
	_, err := q.db.Exec(ctx, addCourseCategory, arg.ID, arg.Category)
	return err
}

const addCoursePrerequisite = `-- name: AddCoursePrerequisite :exec
INSERT INTO course.course_prerequisites(course_id, other_id) VALUES ($1, $2)
`

type AddCoursePrerequisiteParams struct {
	ID      uuid.UUID
	OtherID uuid.UUID
}

func (q *Queries) AddCoursePrerequisite(ctx context.Context, arg AddCoursePrerequisiteParams) error {
	_, err := q.db.Exec(ctx, addCoursePrerequisite, arg.ID, arg.OtherID)
	return err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO course.courses(
    instructor_id,
    title,
    description,
    level,
    price,
    learning_objectives
) VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id
`

type CreateCourseParams struct {
	InstructorID       uuid.UUID
	Title              string
	Description        string
	Level              CourseLevel
	Price              float32
	LearningObjectives string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.InstructorID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Price,
		arg.LearningObjectives,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCourse = `-- name: GetCourse :one
SELECT 
    id,
    instructor_id,
    title,
    subtitle,
    description,
    (
        SELECT ARRAY(
            SELECT name from course.categories
            WHERE id IN (
                SELECT category_id
                FROM course.course_categories c
                WHERE c.course_id = $1
            )
        )
    ) as categories,
    level,
    thumbnail_url,
    promo_video_url,
    price,
    (
        SELECT ARRAY(
            SELECT other_id from course.course_prerequisites
            WHERE course_id = $1
        )
    ) as prerequisites,
    requirements,
    learning_objectives,
    target_audiences
FROM course.courses
WHERE id = $1
`

type GetCourseRow struct {
	ID                 uuid.UUID
	InstructorID       uuid.UUID
	Title              string
	Subtitle           *string
	Description        string
	Categories         interface{}
	Level              CourseLevel
	ThumbnailUrl       *string
	PromoVideoUrl      *string
	Price              float32
	Prerequisites      interface{}
	Requirements       string
	LearningObjectives string
	TargetAudiences    string
}

func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (GetCourseRow, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i GetCourseRow
	err := row.Scan(
		&i.ID,
		&i.InstructorID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Categories,
		&i.Level,
		&i.ThumbnailUrl,
		&i.PromoVideoUrl,
		&i.Price,
		&i.Prerequisites,
		&i.Requirements,
		&i.LearningObjectives,
		&i.TargetAudiences,
	)
	return i, err
}
