// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: course.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addCourseCategory = `-- name: AddCourseCategory :exec
INSERT INTO course.course_categories(course_id, category_id) VALUES (
    $1,
    (SELECT id FROM course.categories WHERE name = $2)
)
`

type AddCourseCategoryParams struct {
	ID       uuid.UUID
	Category string
}

func (q *Queries) AddCourseCategory(ctx context.Context, arg AddCourseCategoryParams) error {
	_, err := q.db.Exec(ctx, addCourseCategory, arg.ID, arg.Category)
	return err
}

const addCoursePrerequisite = `-- name: AddCoursePrerequisite :exec
INSERT INTO course.course_prerequisites(course_id, other_id) VALUES ($1, $2)
`

type AddCoursePrerequisiteParams struct {
	ID      uuid.UUID
	OtherID uuid.UUID
}

func (q *Queries) AddCoursePrerequisite(ctx context.Context, arg AddCoursePrerequisiteParams) error {
	_, err := q.db.Exec(ctx, addCoursePrerequisite, arg.ID, arg.OtherID)
	return err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO course.courses(
    instructor_id,
    title,
    description,
    level,
    price,
    learning_objectives
) VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id
`

type CreateCourseParams struct {
	InstructorID       uuid.UUID
	Title              string
	Description        string
	Level              CourseLevel
	Price              float32
	LearningObjectives string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.InstructorID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Price,
		arg.LearningObjectives,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCourse = `-- name: GetCourse :one
SELECT 
    id,
    instructor_id,
    title,
    subtitle,
    description,
    level,
    thumbnail_url,
    promo_video_url,
    price,
    requirements,
    learning_objectives,
    target_audiences
FROM course.courses
WHERE id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (CourseCourse, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i CourseCourse
	err := row.Scan(
		&i.ID,
		&i.InstructorID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.ThumbnailUrl,
		&i.PromoVideoUrl,
		&i.Price,
		&i.Requirements,
		&i.LearningObjectives,
		&i.TargetAudiences,
	)
	return i, err
}

const getCourseCategories = `-- name: GetCourseCategories :many
SELECT name
FROM course.categories
WHERE id IN (
    SELECT category_id
    FROM course.course_categories c
    WHERE c.course_id = $1
)
`

func (q *Queries) GetCourseCategories(ctx context.Context, id uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getCourseCategories, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePrerequisites = `-- name: GetCoursePrerequisites :many
SELECT other_id
FROM course.course_prerequisites
WHERE course_id = $1
`

func (q *Queries) GetCoursePrerequisites(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getCoursePrerequisites, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var other_id uuid.UUID
		if err := rows.Scan(&other_id); err != nil {
			return nil, err
		}
		items = append(items, other_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
