// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addCourseCategory = `-- name: AddCourseCategory :exec
INSERT INTO general.course_categories(course_id, category_id) VALUES (
    $1,
    (SELECT id FROM general.categories WHERE name = $2)
)
`

type AddCourseCategoryParams struct {
	ID       uuid.UUID
	Category string
}

func (q *Queries) AddCourseCategory(ctx context.Context, arg AddCourseCategoryParams) error {
	_, err := q.db.Exec(ctx, addCourseCategory, arg.ID, arg.Category)
	return err
}

const addCoursePrerequisite = `-- name: AddCoursePrerequisite :exec
INSERT INTO general.course_prerequisites(course_id, other_id) VALUES ($1, $2)
`

type AddCoursePrerequisiteParams struct {
	ID      uuid.UUID
	OtherID uuid.UUID
}

func (q *Queries) AddCoursePrerequisite(ctx context.Context, arg AddCoursePrerequisiteParams) error {
	_, err := q.db.Exec(ctx, addCoursePrerequisite, arg.ID, arg.OtherID)
	return err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO general.courses(
    instructor_id,
    title,
    description,
    level,
    price,
    learning_objectives
) VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id
`

type CreateCourseParams struct {
	InstructorID       uuid.UUID
	Title              string
	Description        string
	Level              GeneralLevel
	Price              float32
	LearningObjectives string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.InstructorID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Price,
		arg.LearningObjectives,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCourseCategories = `-- name: DeleteCourseCategories :exec
DELETE FROM general.course_categories
WHERE course_id = $1
`

func (q *Queries) DeleteCourseCategories(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseCategories, id)
	return err
}

const deleteCoursePrerequisites = `-- name: DeleteCoursePrerequisites :exec
DELETE FROM general.course_prerequisites
WHERE course_id = $1
`

func (q *Queries) DeleteCoursePrerequisites(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoursePrerequisites, id)
	return err
}

const getAllCourses = `-- name: GetAllCourses :many
SELECT id
FROM general.courses
WHERE status = 'draft'
`

func (q *Queries) GetAllCourses(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAllCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourse = `-- name: GetCourse :one
SELECT 
    id,
    instructor_id,
    title,
    subtitle,
    description,
    level,
    thumbnail_url,
    promo_video_url,
    price,
    requirements,
    learning_objectives,
    target_audiences,
    status
FROM general.courses
WHERE id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (GeneralCourse, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i GeneralCourse
	err := row.Scan(
		&i.ID,
		&i.InstructorID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.ThumbnailUrl,
		&i.PromoVideoUrl,
		&i.Price,
		&i.Requirements,
		&i.LearningObjectives,
		&i.TargetAudiences,
		&i.Status,
	)
	return i, err
}

const getCourseCategories = `-- name: GetCourseCategories :many
SELECT name
FROM general.categories
WHERE id IN (
    SELECT category_id
    FROM general.course_categories c
    WHERE c.course_id = $1
)
`

func (q *Queries) GetCourseCategories(ctx context.Context, id uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getCourseCategories, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePrerequisites = `-- name: GetCoursePrerequisites :many
SELECT other_id
FROM general.course_prerequisites
WHERE course_id = $1
`

func (q *Queries) GetCoursePrerequisites(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getCoursePrerequisites, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var other_id uuid.UUID
		if err := rows.Scan(&other_id); err != nil {
			return nil, err
		}
		items = append(items, other_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE general.courses
SET
    title = COALESCE($1, title),
    subtitle = COALESCE($2, subtitle),
    description = COALESCE($3, description),
    level = COALESCE($4, level),
    thumbnail_url = COALESCE($5, thumbnail_url),
    promo_video_url = COALESCE($6, promo_video_url),
    price = COALESCE($7, price),
    requirements = COALESCE($8, requirements),
    learning_objectives = COALESCE($9, learning_objectives),
    target_audiences = COALESCE($10, target_audiences),
    status = COALESCE($11, status)
WHERE id = $12 AND instructor_id = $13
`

type UpdateCourseParams struct {
	Title              *string
	Subtitle           *string
	Description        *string
	Level              NullGeneralLevel
	ThumbnailUrl       *string
	PromoVideoUrl      *string
	Price              *float32
	Requirements       *string
	LearningObjectives *string
	TargetAudiences    *string
	Status             NullGeneralStatus
	ID                 uuid.UUID
	InstructorID       uuid.UUID
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.Exec(ctx, updateCourse,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Level,
		arg.ThumbnailUrl,
		arg.PromoVideoUrl,
		arg.Price,
		arg.Requirements,
		arg.LearningObjectives,
		arg.TargetAudiences,
		arg.Status,
		arg.ID,
		arg.InstructorID,
	)
	return err
}
