// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: material.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO general.materials(
    course_id,
    kind,
    lesson,
    title,
    content,
    required_score,
    required_peers,
    is_required,
    position
) VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    COALESCE((SELECT MAX(position) FROM general.materials WHERE course_id = $1), 0) + 1000
)
RETURNING id
`

type CreateMaterialParams struct {
	CourseID      uuid.UUID
	Kind          GeneralMaterialKind
	Lesson        string
	Title         string
	Content       *string
	RequiredScore *int32
	RequiredPeers *int32
	IsRequired    bool
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.CourseID,
		arg.Kind,
		arg.Lesson,
		arg.Title,
		arg.Content,
		arg.RequiredScore,
		arg.RequiredPeers,
		arg.IsRequired,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMaterialByCourse = `-- name: GetMaterialByCourse :many
SELECT id, course_id, position, kind, lesson, title, content, required_score, required_peers, is_required FROM general.materials WHERE course_id = $1
`

func (q *Queries) GetMaterialByCourse(ctx context.Context, courseID uuid.UUID) ([]GeneralMaterial, error) {
	rows, err := q.db.Query(ctx, getMaterialByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneralMaterial
	for rows.Next() {
		var i GeneralMaterial
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Position,
			&i.Kind,
			&i.Lesson,
			&i.Title,
			&i.Content,
			&i.RequiredScore,
			&i.RequiredPeers,
			&i.IsRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaterial = `-- name: UpdateMaterial :exec
UPDATE general.materials
SET
    position = COALESCE($1, position),
    lesson = COALESCE($2, lesson),
    title = COALESCE($3, title),
    required_score = COALESCE($4, required_score),
    required_peers = COALESCE($5, required_peers),
    is_required = COALESCE($6, is_required)
WHERE id = $7
`

type UpdateMaterialParams struct {
	Position      pgtype.Numeric
	Lesson        *string
	Title         *string
	RequiredScore *int32
	RequiredPeers *int32
	IsRequired    *bool
	ID            uuid.UUID
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) error {
	_, err := q.db.Exec(ctx, updateMaterial,
		arg.Position,
		arg.Lesson,
		arg.Title,
		arg.RequiredScore,
		arg.RequiredPeers,
		arg.IsRequired,
		arg.ID,
	)
	return err
}
