// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: material.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO general.materials(
    course_id,
    kind,
    lesson,
    title,
    content,
    required_score,
    required_peers,
    is_required,
    position
) VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    COALESCE((SELECT MAX(position) FROM general.materials WHERE course_id = $1), 0) + 1000
)
RETURNING id
`

type CreateMaterialParams struct {
	CourseID      uuid.UUID
	Kind          GeneralMaterialKind
	Lesson        string
	Title         string
	Content       *string
	RequiredScore *int32
	RequiredPeers *int32
	IsRequired    bool
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.CourseID,
		arg.Kind,
		arg.Lesson,
		arg.Title,
		arg.Content,
		arg.RequiredScore,
		arg.RequiredPeers,
		arg.IsRequired,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createMaterialAttempt = `-- name: CreateMaterialAttempt :one
INSERT INTO general.material_attempts(material_id, student_id, score)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateMaterialAttemptParams struct {
	MaterialID uuid.UUID
	StudentID  uuid.UUID
	Score      *int32
}

func (q *Queries) CreateMaterialAttempt(ctx context.Context, arg CreateMaterialAttemptParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createMaterialAttempt, arg.MaterialID, arg.StudentID, arg.Score)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMaterialAttempts = `-- name: GetMaterialAttempts :many
SELECT id, material_id, student_id, score, created_at
FROM general.material_attempts
WHERE material_id = $1 AND student_id = $2
`

type GetMaterialAttemptsParams struct {
	MaterialID uuid.UUID
	StudentID  uuid.UUID
}

func (q *Queries) GetMaterialAttempts(ctx context.Context, arg GetMaterialAttemptsParams) ([]GeneralMaterialAttempt, error) {
	rows, err := q.db.Query(ctx, getMaterialAttempts, arg.MaterialID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneralMaterialAttempt
	for rows.Next() {
		var i GeneralMaterialAttempt
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.StudentID,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialPosition = `-- name: GetMaterialPosition :one
SELECT position FROM general.materials WHERE id = $1
`

func (q *Queries) GetMaterialPosition(ctx context.Context, id uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getMaterialPosition, id)
	var position float64
	err := row.Scan(&position)
	return position, err
}

const getMaterialsByCourse = `-- name: GetMaterialsByCourse :many
SELECT id, course_id, position, kind, lesson, title, content, required_score, required_peers, is_required FROM general.materials WHERE course_id = $1
`

func (q *Queries) GetMaterialsByCourse(ctx context.Context, courseID uuid.UUID) ([]GeneralMaterial, error) {
	rows, err := q.db.Query(ctx, getMaterialsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneralMaterial
	for rows.Next() {
		var i GeneralMaterial
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Position,
			&i.Kind,
			&i.Lesson,
			&i.Title,
			&i.Content,
			&i.RequiredScore,
			&i.RequiredPeers,
			&i.IsRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaterial = `-- name: UpdateMaterial :exec
UPDATE general.materials
SET
    position = COALESCE($1, position),
    lesson = COALESCE($2, lesson),
    title = COALESCE($3, title),
    required_score = COALESCE($4, required_score),
    required_peers = COALESCE($5, required_peers),
    is_required = COALESCE($6, is_required)
WHERE id = $7
`

type UpdateMaterialParams struct {
	Position      *float64
	Lesson        *string
	Title         *string
	RequiredScore *int32
	RequiredPeers *int32
	IsRequired    *bool
	ID            uuid.UUID
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) error {
	_, err := q.db.Exec(ctx, updateMaterial,
		arg.Position,
		arg.Lesson,
		arg.Title,
		arg.RequiredScore,
		arg.RequiredPeers,
		arg.IsRequired,
		arg.ID,
	)
	return err
}
