// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type GeneralLevel string

const (
	GeneralLevelBeginner     GeneralLevel = "beginner"
	GeneralLevelIntermediate GeneralLevel = "intermediate"
	GeneralLevelAdvanced     GeneralLevel = "advanced"
)

func (e *GeneralLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GeneralLevel(s)
	case string:
		*e = GeneralLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for GeneralLevel: %T", src)
	}
	return nil
}

type NullGeneralLevel struct {
	GeneralLevel GeneralLevel
	Valid        bool // Valid is true if GeneralLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGeneralLevel) Scan(value interface{}) error {
	if value == nil {
		ns.GeneralLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GeneralLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGeneralLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GeneralLevel), nil
}

type GeneralCategory struct {
	ID   uuid.UUID
	Name string
}

type GeneralCourse struct {
	ID                 uuid.UUID
	InstructorID       uuid.UUID
	Title              string
	Subtitle           *string
	Description        string
	Level              GeneralLevel
	ThumbnailUrl       *string
	PromoVideoUrl      *string
	Price              float32
	Requirements       *string
	LearningObjectives string
	TargetAudiences    *string
}

type GeneralCourseCategory struct {
	ID         uuid.UUID
	CourseID   uuid.UUID
	CategoryID uuid.UUID
}

type GeneralCoursePrerequisite struct {
	ID       uuid.UUID
	CourseID uuid.UUID
	OtherID  uuid.UUID
}
