// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type GeneralLevel string

const (
	GeneralLevelBeginner     GeneralLevel = "beginner"
	GeneralLevelIntermediate GeneralLevel = "intermediate"
	GeneralLevelAdvanced     GeneralLevel = "advanced"
)

func (e *GeneralLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GeneralLevel(s)
	case string:
		*e = GeneralLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for GeneralLevel: %T", src)
	}
	return nil
}

type NullGeneralLevel struct {
	GeneralLevel GeneralLevel
	Valid        bool // Valid is true if GeneralLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGeneralLevel) Scan(value interface{}) error {
	if value == nil {
		ns.GeneralLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GeneralLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGeneralLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GeneralLevel), nil
}

type GeneralMaterialKind string

const (
	GeneralMaterialKindText       GeneralMaterialKind = "text"
	GeneralMaterialKindFile       GeneralMaterialKind = "file"
	GeneralMaterialKindVideo      GeneralMaterialKind = "video"
	GeneralMaterialKindQuiz       GeneralMaterialKind = "quiz"
	GeneralMaterialKindAssignment GeneralMaterialKind = "assignment"
)

func (e *GeneralMaterialKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GeneralMaterialKind(s)
	case string:
		*e = GeneralMaterialKind(s)
	default:
		return fmt.Errorf("unsupported scan type for GeneralMaterialKind: %T", src)
	}
	return nil
}

type NullGeneralMaterialKind struct {
	GeneralMaterialKind GeneralMaterialKind
	Valid               bool // Valid is true if GeneralMaterialKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGeneralMaterialKind) Scan(value interface{}) error {
	if value == nil {
		ns.GeneralMaterialKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GeneralMaterialKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGeneralMaterialKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GeneralMaterialKind), nil
}

type GeneralStatus string

const (
	GeneralStatusDraft      GeneralStatus = "draft"
	GeneralStatusNeedReview GeneralStatus = "need-review"
	GeneralStatusAiApproved GeneralStatus = "ai-approved"
	GeneralStatusApproved   GeneralStatus = "approved"
	GeneralStatusRemoved    GeneralStatus = "removed"
)

func (e *GeneralStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GeneralStatus(s)
	case string:
		*e = GeneralStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GeneralStatus: %T", src)
	}
	return nil
}

type NullGeneralStatus struct {
	GeneralStatus GeneralStatus
	Valid         bool // Valid is true if GeneralStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGeneralStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GeneralStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GeneralStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGeneralStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GeneralStatus), nil
}

type GeneralAttempt struct {
	ID         uuid.UUID
	MaterialID uuid.UUID
	StudentID  uuid.UUID
	Score      *int32
	CreatedAt  time.Time
}

type GeneralAttemptDetail struct {
	AttemptID  uuid.UUID
	QuestionID uuid.UUID
	Answer     string
}

type GeneralCategory struct {
	ID   uuid.UUID
	Name string
}

type GeneralCourse struct {
	ID                 uuid.UUID
	InstructorID       uuid.UUID
	Title              string
	Subtitle           *string
	Description        string
	Level              GeneralLevel
	ThumbnailUrl       *string
	PromoVideoUrl      *string
	Price              float32
	Requirements       *string
	LearningObjectives string
	TargetAudiences    *string
	Status             GeneralStatus
}

type GeneralCourseCategory struct {
	ID         uuid.UUID
	CourseID   uuid.UUID
	CategoryID uuid.UUID
}

type GeneralCoursePrerequisite struct {
	ID       uuid.UUID
	CourseID uuid.UUID
	OtherID  uuid.UUID
}

type GeneralEnroll struct {
	CourseID  uuid.UUID
	StudentID uuid.UUID
	CreatedAt time.Time
}

type GeneralMaterial struct {
	ID            uuid.UUID
	CourseID      uuid.UUID
	Position      float64
	Kind          GeneralMaterialKind
	Lesson        string
	Title         string
	Content       *string
	RequiredScore *int32
	RequiredPeers *int32
	IsRequired    bool
}

type GeneralQuestion struct {
	ID         uuid.UUID
	MaterialID uuid.UUID
	Position   float64
	Question   string
}

type GeneralQuestionCriterium struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Criterion  string
	Score      int32
}

type GeneralQuestionPossibleAnswer struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Answer     string
}
