// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: question.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO general.questions(material_id, position, question) VALUES(
    $1,
    COALESCE((SELECT MAX(position) FROM general.questions WHERE material_id = $1), 0) + 1000,
    $2
)
RETURNING id
`

type CreateQuestionParams struct {
	MaterialID uuid.UUID
	Question   string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createQuestion, arg.MaterialID, arg.Question)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createQuestionCriterion = `-- name: CreateQuestionCriterion :one
INSERT INTO general.question_criteria(question_id, criterion, score)
VALUES($1, $2, $3)
RETURNING id
`

type CreateQuestionCriterionParams struct {
	QuestionID uuid.UUID
	Criterion  string
	Score      int32
}

func (q *Queries) CreateQuestionCriterion(ctx context.Context, arg CreateQuestionCriterionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createQuestionCriterion, arg.QuestionID, arg.Criterion, arg.Score)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createQuestionPossibleAnswer = `-- name: CreateQuestionPossibleAnswer :one
INSERT INTO general.question_possible_answers(question_id, answer)
VALUES($1, $2)
RETURNING id
`

type CreateQuestionPossibleAnswerParams struct {
	QuestionID uuid.UUID
	Answer     string
}

func (q *Queries) CreateQuestionPossibleAnswer(ctx context.Context, arg CreateQuestionPossibleAnswerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createQuestionPossibleAnswer, arg.QuestionID, arg.Answer)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getQuestionCriteria = `-- name: GetQuestionCriteria :many
SELECT id, question_id, criterion, score FROM general.question_criteria WHERE question_id = $1
`

func (q *Queries) GetQuestionCriteria(ctx context.Context, questionID uuid.UUID) ([]GeneralQuestionCriterium, error) {
	rows, err := q.db.Query(ctx, getQuestionCriteria, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneralQuestionCriterium
	for rows.Next() {
		var i GeneralQuestionCriterium
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Criterion,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionPosition = `-- name: GetQuestionPosition :one
SELECT position FROM general.questions WHERE id = $1
`

func (q *Queries) GetQuestionPosition(ctx context.Context, id uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getQuestionPosition, id)
	var position float64
	err := row.Scan(&position)
	return position, err
}

const getQuestionPossibleAnswers = `-- name: GetQuestionPossibleAnswers :many
SELECT answer FROM general.question_possible_answers WHERE question_id = $1
`

func (q *Queries) GetQuestionPossibleAnswers(ctx context.Context, questionID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getQuestionPossibleAnswers, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var answer string
		if err := rows.Scan(&answer); err != nil {
			return nil, err
		}
		items = append(items, answer)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsByMaterial = `-- name: GetQuestionsByMaterial :many
SELECT id, material_id, position, question FROM general.questions WHERE material_id = $1
`

func (q *Queries) GetQuestionsByMaterial(ctx context.Context, materialID uuid.UUID) ([]GeneralQuestion, error) {
	rows, err := q.db.Query(ctx, getQuestionsByMaterial, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneralQuestion
	for rows.Next() {
		var i GeneralQuestion
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.Position,
			&i.Question,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :exec
UPDATE general.questions
SET
    question = COALESCE($1, question),
    position = COALESCE($2, position)
WHERE id = $3
`

type UpdateQuestionParams struct {
	Question *string
	Position *float64
	ID       uuid.UUID
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) error {
	_, err := q.db.Exec(ctx, updateQuestion, arg.Question, arg.Position, arg.ID)
	return err
}
