// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roadmap.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addRoadmapCourse = `-- name: AddRoadmapCourse :exec
INSERT INTO general.roadmap_courses(
    roadmap_id,
    course_id,
    position
)
VALUES(
    $1,
    $2,
    COALESCE((SELECT MAX(position) FROM general.roadmap_courses WHERE roadmap_id = $1), 0) + 1000
)
`

type AddRoadmapCourseParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

func (q *Queries) AddRoadmapCourse(ctx context.Context, arg AddRoadmapCourseParams) error {
	_, err := q.db.Exec(ctx, addRoadmapCourse, arg.ID, arg.CourseID)
	return err
}

const applyRoadmap = `-- name: ApplyRoadmap :exec
INSERT INTO general.student_roadmaps(student_id, roadmap_id)
VALUES($1, $2)
`

type ApplyRoadmapParams struct {
	StudentID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) ApplyRoadmap(ctx context.Context, arg ApplyRoadmapParams) error {
	_, err := q.db.Exec(ctx, applyRoadmap, arg.StudentID, arg.ID)
	return err
}

const createRoadmap = `-- name: CreateRoadmap :one
INSERT INTO general.roadmaps(author_id, title, description)
VALUES($1, $2, $3)
RETURNING id
`

type CreateRoadmapParams struct {
	AuthorID    uuid.UUID
	Title       string
	Description string
}

func (q *Queries) CreateRoadmap(ctx context.Context, arg CreateRoadmapParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRoadmap, arg.AuthorID, arg.Title, arg.Description)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllRoadmaps = `-- name: GetAllRoadmaps :many
SELECT id FROM general.roadmaps
`

func (q *Queries) GetAllRoadmaps(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAllRoadmaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoadmap = `-- name: GetRoadmap :one
SELECT id, author_id, title, description FROM general.roadmaps WHERE id = $1
`

func (q *Queries) GetRoadmap(ctx context.Context, id uuid.UUID) (GeneralRoadmap, error) {
	row := q.db.QueryRow(ctx, getRoadmap, id)
	var i GeneralRoadmap
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const getRoadmapCourse = `-- name: GetRoadmapCourse :many
SELECT course_id
FROM general.roadmap_courses
WHERE roadmap_id = $1
ORDER BY position
`

func (q *Queries) GetRoadmapCourse(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getRoadmapCourse, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var course_id uuid.UUID
		if err := rows.Scan(&course_id); err != nil {
			return nil, err
		}
		items = append(items, course_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoadmapCoursePosition = `-- name: GetRoadmapCoursePosition :one
SELECT position FROM general.roadmap_courses WHERE roadmap_id = $1 AND course_id = $2
`

type GetRoadmapCoursePositionParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

func (q *Queries) GetRoadmapCoursePosition(ctx context.Context, arg GetRoadmapCoursePositionParams) (float64, error) {
	row := q.db.QueryRow(ctx, getRoadmapCoursePosition, arg.ID, arg.CourseID)
	var position float64
	err := row.Scan(&position)
	return position, err
}

const getRoadmapsByStudent = `-- name: GetRoadmapsByStudent :many
SELECT id FROM general.roadmaps
WHERE id IN (
    SELECT roadmap_id
    FROM general.student_roadmaps
    WHERE student_id = $1
)
`

func (q *Queries) GetRoadmapsByStudent(ctx context.Context, studentID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getRoadmapsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoadmap = `-- name: UpdateRoadmap :exec
UPDATE general.roadmaps
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description)
WHERE id = $3
`

type UpdateRoadmapParams struct {
	Title       *string
	Description *string
	ID          uuid.UUID
}

func (q *Queries) UpdateRoadmap(ctx context.Context, arg UpdateRoadmapParams) error {
	_, err := q.db.Exec(ctx, updateRoadmap, arg.Title, arg.Description, arg.ID)
	return err
}

const updateRoadmapCourse = `-- name: UpdateRoadmapCourse :exec
UPDATE general.roadmap_courses
SET position = $1
WHERE roadmap_id = $2 AND course_id = $3
`

type UpdateRoadmapCourseParams struct {
	Posistion float64
	ID        uuid.UUID
	CourseID  uuid.UUID
}

func (q *Queries) UpdateRoadmapCourse(ctx context.Context, arg UpdateRoadmapCourseParams) error {
	_, err := q.db.Exec(ctx, updateRoadmapCourse, arg.Posistion, arg.ID, arg.CourseID)
	return err
}
